src/Spg.AloMalo.MvcFrontEnd/Models/ErrorViewModel.cs
namespace Spg.AloMalo.MvcFrontEnd.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Spg.AloMalo.MvcFrontEnd/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using Spg.AloMalo.DomainModel.Commands;
using Spg.AloMalo.DomainModel.Dtos;
using Spg.AloMalo.DomainModel.Error;
using Spg.AloMalo.DomainModel.Interfaces;
using Spg.AloMalo.DomainModel.Model;

namespace Spg.AloMalo.MvcFrontEnd.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumService _albumService;

        public AlbumController(IAlbumService albumService)
        {
            _albumService = albumService;
        }

        [HttpGet()]
        public IActionResult Index()
        {
            // TODO: Liste laden
            ErrorCheck<IQueryable<AlbumDto>> data = _albumService.GetAllOk();
            return View(data.Value as IQueryable<Album>);
        }

        [HttpGet()]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost()]
        public IActionResult Create(CreateAlbumCommand model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
    }
}

src/Spg.AloMalo.MvcFrontEnd/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Spg.AloMalo.MvcFrontEnd.Models;
using System.Diagnostics;

namespace Spg.AloMalo.MvcFrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Spg.AloMalo.MvcFrontEnd/Views/Album/Create.cshtml
@using Spg.AloMalo.DomainModel.Commands
@model CreateAlbumCommand;

<h1>Create (Baustelle)</h1>

<form method="post">
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>

    <input asp-for="Description" />
    <span asp-validation-for="Description"></span>

    <button type="submit">Senden</button>
</form>

src/Spg.AloMalo.MvcFrontEnd/Views/Album/Index.cshtml
@using Spg.AloMalo.DomainModel.Model
@model IQueryable<Album>;

<h1>Liste alle Fotoalben</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Beschreibung</th>
            <th>Erstellungsdatum</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (Album item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>@item.CreationTimeStamp</td>
            <td><a asp-action="Update" asp-controller="Album" asp-route-name="@item.Name">Update</a></td>
            <td><a>Delete</a></td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="Create" asp-controller="Album">Create</a>

src/Spg.AloMalo.MvcFrontEnd/Views/Album/New.cshtml
@model Spg.AloMalo.DomainModel.Dtos.AlbumDto

@{
    ViewData["Title"] = "New";
}

<h1>New</h1>

<h4>AlbumDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="New">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationTimeStamp" class="control-label"></label>
                <input asp-for="CreationTimeStamp" class="form-control" />
                <span asp-validation-for="CreationTimeStamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Spg.AloMalo.MvcFrontEnd/Views/Home/Index.cshtml
@using Spg.AloMalo.DomainModel.Model

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Spg.AloMalo.MvcFrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alo Malo Photo</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Spg.AloMalo.MvcFrontEnd.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js" defer></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="~/js/site.js" asp-append-version="true" defer></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spg.AloMalo.MvcFrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Spg.AloMalo.MvcFrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>